### PR TITLE
Centralize use of Stm

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Not sure why CI is failing but it seems to be the same as https://github.com/coq-tactician/coq-tactician/actions/runs/6881616735/job/18718359258 on the `coqdev` branch latest merge

**Comment by LasseBlaauwbroek** [comment]
The CI failure is due to https://github.com/coq/coq/issues/18368. Thanks for noticing that.

I assume the reason you want to consolidate this is so that when the STM gets removed it is easier to find an alternative for this code? Sounds reasonable to me.

**Comment by SkySkimmer** [comment]
>I assume the reason you want to consolidate this is so that when the STM gets removed it is easier to find an alternative for this code? 

yes

**Comment by LasseBlaauwbroek** [comment]
Thanks @SkySkimmer.

I retargeted this to the coq8.18 branch and bubbled it up (https://github.com/coq-tactician/coq-tactician/commit/7885853423bc7ac9c40b0e02afb044eefc0fa395). (See [here](https://github.com/coq-tactician/coq-tactician#git-branching-model) for the branching model that Tactician uses.)

**Comment by SkySkimmer** [comment]
>Tactician is currently not yet part of the test-suite of Coq, meaning that we don't get overlays when an API is changed upstream.

outdated?

**Comment by LasseBlaauwbroek** [comment]
Indeed. Fixed. https://github.com/coq-tactician/coq-tactician/commit/6ac7a2b184ac002468fedf78f2a44d5249853a7f

**Pull request closed without merging**
