### PR TITLE
fix features out of memory

### PR DESCRIPTION
**Pull request by Zhang-Liao**

### CODE REVIEW

**Review by LasseBlaauwbroek — APPROVED** [review]
Hi Liao,
Sorry, I completely forgot about this PR, and had been generating datasets with the features before this PR. My mistake. I've rebased this PR on top of the latest coq8.11 branch. Let me know if I did the rebase correctly, and I'll merge.

PS: Next time, when you create a PR it is probably better to create a separate branch for it. Now I ended up pushing my rebase to your main branch...

**Comment by Zhang-Liao** [comment]
> Hi Liao, Sorry, I completely forgot about this PR, and had been generating datasets with the features before this PR. My mistake. I've rebased this PR on top of the latest coq8.11 branch. Let me know if I did the rebase correctly, and I'll merge.
>

I did not compile and actually run the programs. It seems to be fine but the remote bench always failsed. Maybe I need to check what caused the errors in the remote bench.

**Comment by LasseBlaauwbroek** [comment]
Yeah, all checks are failing due to an upstream problem:
```
  Error:  The sources of the following couldn't be obtained, aborting:
            - dose3.5.0.1-1: curl error code 403
```
Will probably go away on its own...

**Comment by LasseBlaauwbroek** [comment]
Seems to be fine, I merged it.

**Pull request merged**
