### PR TITLE
Coq8.11 features

### PR DESCRIPTION
**Pull request by Zhang-Liao**
This is the pull request before the meeting with Bartosz where _k_-NN works well with my new features, but LSHF does not fit well. I am still trying to fix the LSHF issue.

### CODE REVIEW

**Comment by LasseBlaauwbroek** [comment]
Did you close this on purpose?

**Comment by Zhang-Liao** [comment]
Dear Lasse,

Yes, I forgot to duplicate some files.

Best,
Liao

LasseBlaauwbroek <notifications@github.com> 于2021年2月25日周四 下午2:35写道：

**Comment by Zhang-Liao** [comment]
I have added the duplicate files

**Review by LasseBlaauwbroek — APPROVED** [review]
Looks good, thanks

**Pull request merged**
